### ISSUE TITLE
[Question] Can i run this project in php localhost ?

### ISSUE THREAD

**Issue by AnubhabMondal** [h5p/h5p-editor-php-library#110]
If yes,  How can i proceed..?
Can somebody please help me on that .
Thanks.!!

**Comment by icc** [comment]
Of course, this will work on localhost. However, you need to integrate this component into a system first, e.g. like the WordPress, Moodle and Drupal plugin does. You can see how it's done here: https://github.com/h5p/h5p-wordpress-plugin

**Comment by AnubhabMondal** [comment]
@icc Thanks for your quick and valuable replay.
So, the project standalone will not work .. I have to use Moodle, Drupal or Wordpress. Plz, confirm..!!
Sorry, to interrupt you again.
