### ISSUE TITLE
Links URL -> other doesn't work

### ISSUE THREAD

**Issue by Urpokarhu1** [h5p/h5p-editor-php-library#112]
Hello,

When I'm creating a link from a text in course presentation and choose protocal "other" -> type in m-files://address.com -> url turns in to address.com and it drops the custom protocol from the link. This seems like a bug to me or have I understood other-setting wrong?

This happens both in h5p.org and Moodle 3.5.

![url1](https://user-images.githubusercontent.com/53904029/80336074-dfb97c80-885e-11ea-9aed-e9bc5777c845.PNG)

![url2](https://user-images.githubusercontent.com/53904029/80336080-e516c700-885e-11ea-8660-0fdaacc312ce.png)

**Comment by Urpokarhu1** [comment]
This problem persists in Moodle 3.9 & mod_hvp Release 1.21.0

**Comment by otacke** [comment]
@Urpokarhu1 I don't think it's a bug (in H5P.Link by the way). There's a list of allowed protocols that doesn't include your choice `m-files`. https://github.com/h5p/h5p-link/blob/master/link.js#L57

**Comment by Urpokarhu1** [comment]
Hello,

Ok, thanks for the tip 👍
