### ISSUE TITLE
GDPR infringement

### ISSUE THREAD

**Issue by rschrenk** [h5p/h5p-editor-php-library#139]
Hello,

we recognized, that this part of the mod_hvp-Plugin uses Google APIs in 
- https://github.com/h5p/h5p-editor-php-library/blob/1ae19fdb80839b32dad3846d6b0a5c745f8f6187/styles/css/h5p-hub-client.css#L1

As for European sites, this causes an infringement of the GDPR. Would it be possible to fix that?

Kind regards

**Comment by fnoks** [comment]
Thank you for reporting this. We will fix this in the next mod_hvp release.
