### ISSUE TITLE
String hardcoded

### ISSUE THREAD

**Issue by s-cenni** [h5p/h5p-editor-php-library#15]
The string "is required and must have some text or at least an image in it." shouldn't be hard coded so it could be translated.
(https://github.com/h5p/h5p-editor-php-library/blob/751af89ca8c492044437b0b089fe228e061a1bd6/scripts/h5peditor-html.js#L461)

**Comment by fnoks** [comment]
You are absolutely right - this is done by mistake. It should use the language files like the rest av the editor does!
