### ISSUE TITLE
Undefined property: stdClass::$patch_version_in_folder_name

### ISSUE THREAD

**Issue by bvitl** [h5p/h5p-editor-php-library#160]
In PHP log we have:

PHP Warning:  Undefined property: stdClass::$patch_version_in_folder_name in \h5p-editor-php-library\h5peditor.class.php on line 633

**Comment by otacke** [comment]
@bvitl That's what https://github.com/h5p/h5p-editor-php-library/pull/158 is for.

**Comment by bvitl** [comment]
Sorry. Thank you
