### ISSUE TITLE
Replace "-" with "Select content type"

### ISSUE THREAD

**Issue by rlorenzo** [h5p/h5p-editor-php-library#32]
We are using the Moodle version of the H5P plugin and we have a complaint from our support staff that having "-" as the default text for the Editor selection dropdown was confusing. Can it be changed to a more user friendly wording, such as "Select content type"?

We tried making an edit by changing this line: https://github.com/h5p/h5p-editor-php-library/blob/1c8454f235c09e437db5d364c6a119519bc90f72/scripts/h5peditor-library-selector.js#L15

However that approach would involve a hard coding of an English string. To pass in language strings would be more involved and would most likely involve something that you guys would need to implement.

**Comment by falcon-git** [comment]
I understand what you mean. Luckily that dropdown will be completely replaced with something more visual in the next release. I'm closing this issue since we will fix it with the new dropdown.

**Comment by falcon-git** [comment]
icc pointed out that it is only for the top level selector in the next release. The old selector will be there for sub-content, but will be replace for sub-content as well soon.
