### ISSUE TITLE
LibrarySelector API

### ISSUE THREAD

**Issue by SergeyYukhnevich** [h5p/h5p-editor-php-library#35]
Hello guys,

Is there any public API for LibrarySelector with your new H5P selector hub?

I need some event to listen for library change and get selected library.

I went through you code and find out that there are several method that might help me such as `H5PEditor.Editor.prototype.getLibrary`, `H5PEditor.LibrarySelector.prototype.getCurrentLibrary` but I can get this methods only from editor instance. Is there editor instance exposed?

**Comment by tajakobsen** [comment]
Hi Sergey,

The APIs are not intended to be public, but there might be ways you can tap into them. If you tell us what you are trying to achieve, it might be easier to point you in the right direction.

Is it in the view (not the editor) you are trying to find out which library is used? Then the global `H5PIntegration` variable might tell you what you need to know.

**Comment by SergeyYukhnevich** [comment]
Hi Tom,

I've made a [pull request](https://github.com/h5p/h5p-editor-php-library/pull/36), it gives me ability to work with h5peditor and listen to different events.

The goal i need to achieve is to get currently selected library and listen to some event that should be triggered when the library is changed and get new selected library.

**Comment by SergeyYukhnevich** [comment]
this issue is solved in that pull request #36
